### PR TITLE
Upstream upgrade

### PR DESCRIPTION
**Pull request by fernandomora**

### CODE REVIEW

**Comment by azagniotov** [comment]
@fernandomora thank you so much for your PR! Unfortunately some things have changed since `v3.3.0`. Would you be able to address the conflicts?

**Comment by fernandomora** [comment]
Actually, I sent this PR by mistake (I wanted to merge upstream change in my fork) :)
It adds the ability to deploy stubby4j in heroku easily using a button added in main page README as you can see in https://github.com/fernandomora/stubby4j-heroku
Now, I think it's not fully polished to be merged to upstream repo. If you think it would interesting to merge I will rebase, fix conflicts and adjust it a little.

**Comment by azagniotov** [comment]
Go for it. Please resolve the conflicts, polish it and I will merge it.

**Comment by azagniotov** [comment]
@fernandomora I am closing this for now. Feel free to issue a new PR when you are ready. Btw, you should really update your master from mine, I did A LOT of house cleaning. Happy New Year!!

**Pull request closed without merging**
