### PR TITLE
add multiarch Docker support via buildx

### PR DESCRIPTION
**Pull request by fbscarel-bl**

### CODE REVIEW

**Comment by azagniotov** [comment]
@fbscarel-bl Hi. Apologies for the such a late response. Can you please re-open the PR? I would like to merge it

**Comment by azagniotov** [comment]
I achieved some progress with publishing multiple arch images, see the latest-jre11: https://hub.docker.com/layers/azagniotov/stubby4j/latest-jre11/images/sha256-22a50332f75497b65a876ed245aefedda736c4e0b09dff81d389cc661240f0ca?context=explore 

But, please do not use. I need to clean up the PR first: https://github.com/azagniotov/stubby4j/pull/465

**Comment by fbscarel-bl** [comment]
The project that uses stubby4j on my company is on JDK 17, which is why I
"ported" your script to that. Seemed to work well.
To be honest the image has been working fine so far, but thanks for the
update. The buildx stuff is really powerful.

**Comment by azagniotov** [comment]
I will add JDK 17 image too now, by reusing your PR state

**Comment by azagniotov** [comment]
@fbscarel-bl Just as FYI, the JRE 17 is up: https://hub.docker.com/r/azagniotov/stubby4j/tags 

Would you be able to sanity check the ARM 64 image?

**Pull request closed without merging**
