### PR TITLE
Dynamic token replacement in stubbed response has been applied for re…

### PR DESCRIPTION
**Pull request by dzmitryh**
…sponse headers as well.

Hi There,

Yesterday faced with issue when I can't use token replacement in response headers. So for example I can't define regex group somewhere in request and then use it in response header like "location" but only in response body. So decided to fix it. Please advise in case of any concerns how to do it in the best way.

Thanks, Dzmitry.

### CODE REVIEW

**Comment by azagniotov** [comment]
Hi @dzmitryh ,
Thank you for your PR. That's pretty much the right place to do it. I do have a request for you before I merge it, would you be able to add a unit test for this use case? You can add the test(s) in unit/java/io/github/azagniotov/stubby4j/yaml/stubs/StubResponseTest.java

**Comment by dzmitryh** [comment]
Hi @azagniotov,

I've added test to verify that scenario. Please check it out.

Thanks, Dima.

**Comment by azagniotov** [comment]
Awesome, thanks @dzmitryh !

**Comment by azagniotov** [comment]
Dima, just FYI - did a very very minor code cleanup in the areas where you touched the code, just some cosmetic refactoring.

**Comment by dzmitryh** [comment]
@azagniotov cool. Thanks so much!

**Comment by azagniotov** [comment]
@dzmitryh I just released version 4.0.5 (wait for Maven sync), in other words: your feature went live.

**Comment by dzmitryh** [comment]
Hi Alexander,

That’s awesome! Thanks for such helpful tool btw ;) And Happy New Year!

Thanks in advance, Dzmitry.

**Comment by azagniotov** [comment]
Thank you! S Novim Nastupayushim Godom!

**Pull request merged**
