### PR TITLE
Issue#100 Update org.yaml:snakeyaml:1.23

### PR DESCRIPTION
**Pull request by moleksyuk**
Pull request for issue #100

### CODE REVIEW

**Comment by asarkar** [comment]
While you're at it, would you mind upgrading Gradle too?

**Comment by moleksyuk** [comment]
> While you're at it, would you mind upgrading Gradle too?

@asarkar Unfortunately no, because there is gradle 2.0 and the latest 5.1.1. It requires a lot of changes in build project tasks.
And I think it should be in separate pull request.

**Comment by azagniotov** [comment]
Just released 6.0.2.

**Comment by azagniotov** [comment]
I upgraded stubby4j to Gradle `v6.2.2`. Also, the project Gradle setup has been greatly simplified and cleaned up

**Pull request merged**
